# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: MyTitle
email: ruxandrasimion93@gmail.com
# Write an awesome description for your new site here. You can edit this
# line in _config.yml. It will appear in your document head meta (for
# Google search results) and in your feed.xml site description.
description: >- # this means to ignore newlines until "baseurl:"
  My description
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ruxandraS.github.io" # the base hostname & protocol for your site, e.g. http://example.com
abouturl: "/about"
blogurl: "/recent_blogposts"
sidebar_home_link: home
sidebar_about_link: about
sidebar_recent_link: recent
sidebar_repo_link: repo

social:
  - name: GitHub
    icon: github
    username: ruxandraS
    url: https://github.com/ruxandraS

  - name: IRC
    icon: irc
    username: ruxandrasimion
    url: 

  - name: LinkedIn
    icon: linkedin
    username: ruxandraS
    url: https://www.linkedin.com/in/ruxandraS/

  - name: Twitter
    icon: twitter
    username: blubell13
    url: https://twitter.com/blubell13

  # - name: Instagram
  #   icon: instagram
  #   username: roo_kse
  #   url: https://instagram.com/roo_kse

  # - name: Behance
  #   icon: behance
  #   username: 
  #   url:

  # - name: Facebook
  #   icon: facebook
  #   username: 
  #   url:

  # - name: Messenger
  #   icon: messenger
  #   username: 
  #   url:

# Build settings
plugins: [jekyll-paginate]
disqus:
  shortname: https-ruxandras-github-io
markdown: kramdown
paginate: 4 
paginate_path: "recent_blogposts/page:num/"
timezone: Europe/Bucharest

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
